name: Docker Image,Push to GitHub Registry

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/son7211/test_action/john_test:1.3
      
    - name : docker login
      run: docker login -u son7211 -p {{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      
    - name: Docker Push
      run: docker push docker.pkg.github.com/son7211/test_action/john_test:1.3
