name: Docker Image,Push to GitHub Registry

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag john-test:v0.3 
      
    - name : docker login
      run: docker login -u ${{ github.actor }} -p {{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    
    - name: Tag
      run: docker tag john-test:v0.3 docker.pkg.github.com//son7211/ttaacklee/john_test:1.3
      
    - name: Docker Push
      run: docker push docker.pkg.github.com/son7211/ttaacklee/john_test:1.3
